-- MediaCrawler 数据库架构
-- 创建时间: 2024-01-XX
-- 最后更新: 2025-07-31

-- 爬取任务表
CREATE TABLE `crawler_tasks` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `platform` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `task_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `crawler_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT 'search' COMMENT '爬取类型：search(关键词搜索)、detail(指定内容)、creator(创作者主页)',
  `creator_ref_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创作者引用ID（当crawler_type为creator时，关联unified_creator表）',
  `keywords` text COLLATE utf8mb4_unicode_ci,
  `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  `progress` float DEFAULT '0',
  `result_count` int(11) DEFAULT '0',
  `error_message` text COLLATE utf8mb4_unicode_ci,
  `user_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '用户ID',
  `params` text COLLATE utf8mb4_unicode_ci COMMENT '任务参数JSON',
  `priority` int(11) DEFAULT '0' COMMENT '优先级',
  `is_favorite` tinyint(1) DEFAULT '0' COMMENT '是否收藏',
  `deleted` tinyint(1) DEFAULT '0' COMMENT '是否删除',
  `is_pinned` tinyint(1) DEFAULT '0' COMMENT '是否置顶',
  `ip_address` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'IP地址',
  `user_security_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '用户安全ID',
  `user_signature` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '用户签名',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `started_at` timestamp NULL DEFAULT NULL,
  `completed_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_crawler_tasks_platform` (`platform`),
  KEY `idx_crawler_tasks_status` (`status`),
  KEY `idx_crawler_tasks_user_id` (`user_id`),
  KEY `idx_crawler_tasks_created_at` (`created_at`),
  KEY `idx_crawler_tasks_crawler_type` (`crawler_type`),
  KEY `idx_crawler_tasks_creator_ref_id` (`creator_ref_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 统一内容表
CREATE TABLE `unified_content` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `content_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '内容ID',
  `platform` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '平台名称',
  `content_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '内容类型',
  `task_id` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '任务ID',
  `source_keyword` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '来源关键词',
  `title` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '标题',
  `description` text COLLATE utf8mb4_unicode_ci COMMENT '描述',
  `content` longtext COLLATE utf8mb4_unicode_ci COMMENT '内容',
  `author_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '作者ID',
  `author_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '作者名称',
  `author_avatar` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '作者头像',
  `publish_time` timestamp NULL DEFAULT NULL COMMENT '发布时间',
  `create_time` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `video_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '视频URL',
  `video_play_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '视频播放URL',
  `video_download_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '视频下载URL',
  `cover_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '封面URL',
  `image_urls` text COLLATE utf8mb4_unicode_ci COMMENT '图片URL列表(JSON)',
  `comment_count` int(11) DEFAULT '0' COMMENT '评论数',
  `like_count` int(11) DEFAULT '0' COMMENT '点赞数',
  `share_count` int(11) DEFAULT '0' COMMENT '分享数',
  `collect_count` int(11) DEFAULT '0' COMMENT '收藏数',
  `view_count` int(11) DEFAULT '0' COMMENT '播放数',
  `tags` text COLLATE utf8mb4_unicode_ci COMMENT '标签(JSON)',
  `extra_info` text COLLATE utf8mb4_unicode_ci COMMENT '额外信息(JSON)',
  `raw_data` longtext COLLATE utf8mb4_unicode_ci COMMENT '原始数据(JSON)',
  `add_ts` int(11) DEFAULT NULL COMMENT '添加时间戳',
  `last_modify_ts` int(11) DEFAULT NULL COMMENT '最后修改时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_content_platform_id` (`platform`,`content_id`),
  KEY `idx_unified_content_platform` (`platform`),
  KEY `idx_unified_content_task_id` (`task_id`),
  KEY `idx_unified_content_author_id` (`author_id`),
  KEY `idx_unified_content_publish_time` (`publish_time`),
  KEY `idx_unified_content_add_ts` (`add_ts`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 统一创作者表
CREATE TABLE `unified_creator` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `creator_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '创作者ID',
  `platform` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '平台名称',
  `creator_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创作者名称',
  `creator_nickname` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创作者昵称',
  `creator_avatar` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创作者头像',
  `creator_signature` text COLLATE utf8mb4_unicode_ci COMMENT '创作者签名',
  `follower_count` int(11) DEFAULT '0' COMMENT '粉丝数',
  `following_count` int(11) DEFAULT '0' COMMENT '关注数',
  `video_count` int(11) DEFAULT '0' COMMENT '视频数',
  `like_count` int(11) DEFAULT '0' COMMENT '获赞数',
  `raw_data` longtext COLLATE utf8mb4_unicode_ci COMMENT '原始数据(JSON)',
  `add_ts` int(11) DEFAULT NULL COMMENT '添加时间戳',
  `last_modify_ts` int(11) DEFAULT NULL COMMENT '最后修改时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_creator_platform_id` (`platform`,`creator_id`),
  KEY `idx_unified_creator_platform` (`platform`),
  KEY `idx_unified_creator_name` (`creator_name`),
  KEY `idx_unified_creator_add_ts` (`add_ts`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 统一评论表
CREATE TABLE `unified_comment` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `comment_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '评论ID',
  `platform` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '平台名称',
  `content_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '内容ID',
  `author_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '评论作者ID',
  `author_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '评论作者名称',
  `author_avatar` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '评论作者头像',
  `content` text COLLATE utf8mb4_unicode_ci COMMENT '评论内容',
  `publish_time` timestamp NULL DEFAULT NULL COMMENT '发布时间',
  `like_count` int(11) DEFAULT '0' COMMENT '点赞数',
  `reply_count` int(11) DEFAULT '0' COMMENT '回复数',
  `parent_comment_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '父评论ID',
  `raw_data` longtext COLLATE utf8mb4_unicode_ci COMMENT '原始数据(JSON)',
  `add_ts` int(11) DEFAULT NULL COMMENT '添加时间戳',
  `last_modify_ts` int(11) DEFAULT NULL COMMENT '最后修改时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_comment_platform_id` (`platform`,`comment_id`),
  KEY `idx_unified_comment_platform` (`platform`),
  KEY `idx_unified_comment_content_id` (`content_id`),
  KEY `idx_unified_comment_author_id` (`author_id`),
  KEY `idx_unified_comment_publish_time` (`publish_time`),
  KEY `idx_unified_comment_add_ts` (`add_ts`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 