version: '3.8'

services:
  # MinIO对象存储服务
  minio:
    image: minio/minio:latest
    container_name: mediacrawler-minio
    ports:
      - "9000:9000"      # API端口
      - "9001:9001"      # 控制台端口
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - mediacrawler-network

  # MySQL数据库服务
  mysql:
    image: mysql:8.0
    container_name: mediacrawler-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mediacrawler
      MYSQL_USER: mediacrawler
      MYSQL_PASSWORD: mediacrawler123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - mediacrawler-network

  # Redis缓存服务（可选）
  redis:
    image: redis:7-alpine
    container_name: mediacrawler-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - mediacrawler-network

  # Nginx反向代理（可选，用于文件访问）
  nginx:
    image: nginx:alpine
    container_name: mediacrawler-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data:/app/data:ro
    depends_on:
      - minio
    restart: unless-stopped
    networks:
      - mediacrawler-network

volumes:
  minio_data:
    driver: local
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  mediacrawler-network:
    driver: bridge 