# 开发环境配置文件
# 使用方式: ENV=development python main.py

# ==================== 代理配置 ====================
proxy:
  # 代理提供商配置
  provider_name: "qingguo"  # 可选: qingguo, kuaidaili, jisuhttp
  enabled: true
  pool_count: 5
  validate_ip: true
  
  # 青果代理配置
  qingguo_key: "your_qingguo_key_here"
  qingguo_pwd: "your_qingguo_pwd_here"  # 可选
  
  # 快代理配置
  kuaidaili_secret_id: "your_kuaidaili_secret_id"
  kuaidaili_signature: "your_kuaidaili_signature"
  kuaidaili_user_name: "your_kuaidaili_username"
  kuaidaili_user_pwd: "your_kuaidaili_password"
  
  # 极速HTTP代理配置
  jisu_http_key: "your_jisu_http_key"

# ==================== 爬虫配置 ====================
crawler:
  # 爬虫基础配置
  platform: "xhs"  # 可选: xhs, dy, ks, bili, wb, tieba, zhihu
  keywords: "编程副业,编程兼职"
  login_type: "qrcode"  # 可选: qrcode, phone, cookie
  crawler_type: "search"  # 可选: search, detail, creator
  max_notes_count: 50  # 开发环境设置较小的数量
  enable_comments: true
  enable_sub_comments: false
  enable_images: false
  save_data_option: "db"  # 可选: json, csv, db
  headless: false  # 开发环境显示浏览器
  max_sleep_sec: 3  # 开发环境增加间隔
  max_concurrency: 1  # 开发环境单线程

# ==================== 数据库配置 ====================
database:
  host: "192.168.31.231"
  port: 3306
  username: "aiuser"
  password: "edcghj98578"
  database: "mediacrawler"
  charset: "utf8mb4"

# ==================== Redis配置 ====================
redis:
  host: "localhost"
  port: 6379
  db: 0
  password: ""  # 本地Redis无密码
  connection_pool_size: 10
  max_connections: 100
  socket_timeout: 5
  socket_connect_timeout: 5
  socket_keepalive: true
  socket_keepalive_options: {}
  health_check_interval: 30
  retry_on_timeout: true
  
  # 任务结果缓存配置
  task_result_ttl: 604800  # 7天过期时间
  task_result_key_prefix: "mediacrawler:task:"
  
  # 会话缓存配置
  session_ttl: 3600  # 1小时过期时间
  session_key_prefix: "mediacrawler:session:"

# ==================== 应用配置 ====================
app:
  debug: true
  log_level: "DEBUG"
  data_dir: "/app/data"
  user_data_dir: "%s_user_data_dir"

# ==================== 远程桌面配置 ====================
remote_desktop:
  enabled: true
  vnc_url: "http://192.168.31.231:6080/vnc.html"  # 开发环境VNC地址
  vnc_host: "192.168.31.231"
  vnc_port: 6080
  vnc_password: ""
  display_number: 1
  connection_timeout: 5
  max_wait_time: 1800  # 30分钟
  check_interval: 3    # 3秒检查一次 

# ==================== 存储配置 ====================
storage:
  # 本地存储配置
  local_base_path: "/app/data"
  small_file_threshold: 10485760  # 10MB
  
  # MinIO配置
  enable_minio: false  # 开发环境默认关闭
  minio_endpoint: "192.168.31.231:9000"
  minio_access_key: "minioadmin"
  minio_secret_key: "minioadmin"
  minio_secure: false
  minio_bucket: "mediacrawler-videos"
  
  # 数据库配置
  database_url: "mysql+pymysql://aiuser:edcghj98578@192.168.31.231:3306/mediacrawler"
  pool_size: 10
  max_overflow: 20
  pool_timeout: 30
  pool_recycle: 3600
  
  # 文件管理配置
  naming_pattern: "{platform}/{date}/{content_id}/{filename}"
  date_format: "%Y/%m/%d"
  supported_formats:
    - "mp4"
    - "avi"
    - "mov"
    - "mkv"
    - "flv" 
    - "webm"
    - "m4v"
    - "3gp"
  
  # 文件大小限制
  max_file_size: 1073741824  # 1GB
  min_file_size: 1024  # 1KB
  
  # 重复文件处理
  duplicate_check: true
  duplicate_strategy: "skip"
  
  # 文件清理策略
  cleanup:
    enabled: false
    retention_days: 30
    cleanup_interval_hours: 24
  
  # 性能优化配置
  max_concurrent_downloads: 3  # 开发环境减少并发
  chunk_size: 8192
  download_timeout: 300
  max_retries: 3
  retry_delay: 5
  
  # 监控配置
  storage_usage_threshold: 0.8
  file_count_threshold: 10000
  monitor_interval: 3600

# ==================== 服务配置 ====================
server:
  port: 8000
  host: "0.0.0.0"
  debug: true  # 开发环境启用调试
  enable_cors: true
  static_path: "static"
  max_upload_size: 100

# ==================== 安全配置 ====================
security:
  enable_https: false
  ssl_cert: ""
  ssl_key: ""
  session_secret: "dev-secret-key"
  session_expire: 86400
  enable_api_auth: false
  api_key: "dev-api-key"

# ==================== 爬虫服务配置 ====================
crawler_service:
  max_processes: 3  # 开发环境减少进程数
  task_timeout: 1800
  result_cache_time: 3600
  enable_monitoring: true
  monitor_interval: 30
  cpu_warning_threshold: 80
  memory_warning_threshold: 85
  disk_warning_threshold: 90

# ==================== 任务管理配置 ====================
task_management:
  max_queue_size: 50  # 开发环境减少队列大小
  max_retry_count: 3
  retry_interval: 60
  status_check_interval: 10
  result_retention_days: 7  # 开发环境减少保留时间

# ==================== 性能优化配置 ====================
performance:
  enable_cache: true
  cache_size_limit: 50  # 开发环境减少缓存
  enable_compression: true
  enable_async: true
  async_queue_size: 20  # 开发环境减少队列
  async_timeout: 300

# ==================== 监控配置 ====================
monitoring:
  enable_system_monitor: true
  data_retention_days: 3  # 开发环境减少保留时间
  collection_interval: 60
  enable_alerts: true
  alerts:
    cpu_threshold: 80
    memory_threshold: 85
    disk_threshold: 90
    response_time_threshold: 5000

# ==================== 开发环境配置 ====================
development:
  enable_hot_reload: true  # 开发环境启用热重载
  enable_debug_toolbar: true  # 开发环境启用调试工具栏
  enable_detailed_errors: true  # 开发环境显示详细错误
  test_mode: true  # 开发环境启用测试模式

# ==================== 任务隔离配置 ====================
task_isolation:
  # 任务隔离模式
  isolation_mode: "strict"  # strict: 完全隔离, shared: 共享资源
  
  # 任务并发控制
  max_concurrent_tasks: 5  # 开发环境减少并发数
  max_tasks_per_session: 20  # 开发环境减少任务数
  
  # 资源隔离
  enable_resource_isolation: true
  enable_cross_task_data_access: false
  
  # 认证预留接口
  auth_middleware_enabled: false  # 预留：将来集成用户认证
  auth_token_header: "Authorization"
  auth_session_timeout: 7200  # 2小时

# ==================== 词云配置 ====================
wordcloud:
  enable_get_wordcloud: false
  custom_words:
    "零几": "年份"
    "高频词": "专业术语"
  stop_words_file: "./docs/hit_stopwords.txt"
  font_path: "./docs/STZHONGS.TTF"

# ==================== 基础配置 ====================
ua: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0'
save_login_state: true 