# 存储配置
storage:
  # 本地存储配置
  local_base_path: "./data" # 当部署到服务器时，需要修改为 /app/files
  small_file_threshold: 10485760  # 10MB，小于此大小的文件存储到本地
  
  # MinIO配置
  enable_minio: true  # 是否启用MinIO
  minio_endpoint: "192.168.31.231:9000"
  minio_access_key: "minioadmin"
  minio_secret_key: "your_minio_password_123"
  minio_secure: false  # 是否使用HTTPS
  minio_bucket: "mediacrawler-videos"
  
  # 数据库配置
  database:
    url: "mysql+pymysql://aiuser:edcghj98578@localhost:3306/mediacrawler"
    pool_size: 10
    max_overflow: 20
    pool_timeout: 30
    pool_recycle: 3600
  
  # 文件管理配置
  file_management:
    # 文件命名规则
    naming_pattern: "{platform}/{date}/{content_id}/{filename}"
    date_format: "%Y/%m/%d"
    
    # 文件类型支持
    supported_formats:
      - "mp4"
      - "avi"
      - "mov"
      - "mkv"
      - "flv" 
      - "webm"
      - "m4v"
      - "3gp"
    
    # 文件大小限制
    max_file_size: 1073741824  # 1GB
    min_file_size: 1024  # 1KB
    
    # 重复文件处理
    duplicate_check: true
    duplicate_strategy: "skip"  # skip/overwrite/rename
    
    # 文件清理策略
    cleanup:
      enabled: false
      retention_days: 30
      cleanup_interval_hours: 24
  
  # 性能优化配置
  performance:
    # 并发下载数
    max_concurrent_downloads: 5
    
    # 分块下载大小
    chunk_size: 8192
    
    # 下载超时时间
    download_timeout: 300
    
    # 重试配置
    max_retries: 3
    retry_delay: 5
  
  # 监控配置
  monitoring:
    # 存储使用率告警阈值
    storage_usage_threshold: 0.8  # 80%
    
    # 文件数量告警阈值
    file_count_threshold: 10000
    
    # 监控间隔（秒）
    monitor_interval: 3600 