# 生产环境配置文件
# 使用方式: ENV=production python main.py

proxy:
  # 代理提供商配置
  provider_name: "qingguo"  # 生产环境推荐使用青果代理
  enabled: true
  pool_count: 20  # 生产环境增加代理池大小
  validate_ip: true
  
  # 青果代理配置
  qingguo_key: "${QINGGUO_KEY}"  # 从环境变量读取敏感信息
  qingguo_pwd: "${QINGGUO_PWD}"  # 可选
  
  # 快代理配置
  kuaidaili_secret_id: "${KUAIDAILI_SECRET_ID}"
  kuaidaili_signature: "${KUAIDAILI_SIGNATURE}"
  kuaidaili_user_name: "${KUAIDAILI_USERNAME}"
  kuaidaili_user_pwd: "${KUAIDAILI_PASSWORD}"
  
  # 极速HTTP代理配置
  jisu_http_key: "${JISU_HTTP_KEY}"

crawler:
  # 爬虫基础配置
  platform: "xhs"
  keywords: "编程副业,编程兼职"
  login_type: "qrcode"
  crawler_type: "search"
  max_notes_count: 500  # 生产环境增加爬取数量
  enable_comments: true
  enable_sub_comments: false
  enable_images: false
  save_data_option: "db"  # 生产环境推荐使用数据库
  headless: true  # 生产环境无头模式
  max_sleep_sec: 1  # 生产环境减少间隔提高效率
  max_concurrency: 3  # 生产环境多线程

database:
  # 数据库配置
  host: "192.168.31.231"
  port: 3306
  username: "aiuser"
  password: "edcghj98578"
  database: "mediacrawler"
  charset: "utf8mb4"

redis:
  # Redis缓存配置
  host: "localhost"
  port: 6379
  db: 0
  password: ""  # 本地Redis无密码
  connection_pool_size: 10
  max_connections: 100
  socket_timeout: 5
  socket_connect_timeout: 5
  socket_keepalive: true
  socket_keepalive_options: {}
  health_check_interval: 30
  retry_on_timeout: true
  
  # 任务结果缓存配置
  task_result_ttl: 604800  # 7天过期时间
  task_result_key_prefix: "mediacrawler:task:"
  
  # 会话缓存配置
  session_ttl: 3600  # 1小时过期时间
  session_key_prefix: "mediacrawler:session:"

app:
  # 应用配置
  debug: false
  log_level: "INFO"
  data_dir: "./data/prod"
  user_data_dir: "%s_user_data_dir_prod"

remote_desktop:
  # 远程桌面配置
  enabled: true
  vnc_url: "${VNC_URL:-http://localhost:6080/vnc.html}"  # 生产环境从环境变量读取
  vnc_host: "${VNC_HOST:-localhost}"
  vnc_port: ${VNC_PORT:-6080}
  vnc_password: "${VNC_PASSWORD:-}"
  display_number: ${DISPLAY_NUMBER:-1}
  connection_timeout: 5
  max_wait_time: 1800  # 30分钟
  check_interval: 3    # 3秒检查一次 