# 本地环境配置文件
# 使用方式: ENV=local python main.py

# ==================== 代理配置 ====================
proxy:
  # 代理提供商配置
  provider_name: "qingguo"  # 可选: qingguo, kuaidaili, jisuhttp
  enabled: false  # 本地环境建议关闭，避免资源消耗
  pool_count: 5
  validate_ip: true
  
  # 青果代理配置
  qingguo_key: "your_qingguo_key_here"
  qingguo_pwd: "your_qingguo_pwd_here"  # 可选
  
  # 快代理配置
  kuaidaili_secret_id: "your_kuaidaili_secret_id"
  kuaidaili_signature: "your_kuaidaili_signature"
  kuaidaili_user_name: "your_kuaidaili_username"
  kuaidaili_user_pwd: "your_kuaidaili_password"
  
  # 极速HTTP代理配置
  jisu_http_key: "your_jisu_http_key"

# ==================== 爬虫配置 ====================
crawler:
  # 爬虫基础配置
  platform: "xhs"  # 可选: xhs, dy, ks, bili, wb, tieba, zhihu
  keywords: "编程副业,编程兼职"
  login_type: "qrcode"  # 可选: qrcode, phone, cookie
  crawler_type: "search"  # 可选: search, detail, creator
  max_notes_count: 20  # 减少爬取数量，避免资源占用过多
  enable_comments: false  # 暂时关闭评论爬取，减少资源消耗
  enable_sub_comments: false
  enable_images: false  # 关闭图片下载，减少资源消耗
  save_data_option: "db"  # 可选: json, csv, db
  headless: true  # Linux服务器环境无头模式
  max_sleep_sec: 5  # 增加间隔时间，减少请求频率
  max_concurrency: 2  # 适度增加并发数，但不要太高

# ==================== 数据库配置 ====================
database:
  host: "192.168.31.231"
  port: 3306
  username: "aiuser"
  password: "edcghj98578"
  database: "mediacrawler"
  charset: "utf8mb4"

# ==================== Redis配置 ====================
redis:
  host: "localhost"
  port: 6379
  db: 0
  password: "your_redis_password_123"  # 本地Redis无密码
  connection_pool_size: 5  # 减少连接池大小
  max_connections: 20  # 减少最大连接数
  socket_timeout: 5
  socket_connect_timeout: 5
  socket_keepalive: true
  socket_keepalive_options: {}
  health_check_interval: 30
  retry_on_timeout: true
  
  # 任务结果缓存配置
  task_result_ttl: 604800  # 7天过期时间
  task_result_key_prefix: "mediacrawler:task:"
  
  # 会话缓存配置
  session_ttl: 3600  # 1小时过期时间
  session_key_prefix: "mediacrawler:session:"

# ==================== 应用配置 ====================
app:
  debug: true
  log_level: "INFO"  # 降低日志级别，减少I/O开销
  data_dir: "/home/yxdevuser1/Projects/pyProjects/AiVideoProjects/media_crawler/data"
  user_data_dir: "%s_user_data_dir"

# ==================== 远程桌面配置 ====================
remote_desktop:
  enabled: true
  vnc_url: "http://192.168.31.231:6080/vnc.html"  # 本地环境VNC地址
  vnc_host: "192.168.31.231"
  vnc_port: 6080
  vnc_password: ""
  display_number: 1
  connection_timeout: 5
  max_wait_time: 1800  # 30分钟
  check_interval: 3    # 3秒检查一次

# ==================== 存储配置 ====================
storage:
  # 本地存储配置
  local_base_path: "./data"  # 当部署到服务器时，需要修改为 /app/files
  small_file_threshold: 10485760  # 10MB，小于此大小的文件存储到本地
  
  # MinIO配置
  enable_minio: true  # 是否启用MinIO
  minio_endpoint: "192.168.31.231:9000"
  minio_access_key: "minioadmin"
  minio_secret_key: "your_minio_password_123"
  minio_secure: false  # 是否使用HTTPS
  minio_bucket: "mediacrawler-videos"
  
  # 数据库配置
  database_url: "mysql+pymysql://aiuser:edcghj98578@localhost:3306/mediacrawler"
  pool_size: 10
  max_overflow: 20
  pool_timeout: 30
  pool_recycle: 3600
  
  # 文件管理配置
  naming_pattern: "{platform}/{date}/{content_id}/{filename}"
  date_format: "%Y/%m/%d"
  supported_formats:
    - "mp4"
    - "avi"
    - "mov"
    - "mkv"
    - "flv" 
    - "webm"
    - "m4v"
    - "3gp"
  
  # 文件大小限制
  max_file_size: 1073741824  # 1GB
  min_file_size: 1024  # 1KB
  
  # 重复文件处理
  duplicate_check: true
  duplicate_strategy: "skip"  # skip/overwrite/rename
  
  # 文件清理策略
  cleanup:
    enabled: false
    retention_days: 30
    cleanup_interval_hours: 24
  
  # 性能优化配置
  max_concurrent_downloads: 5
  chunk_size: 8192
  download_timeout: 300
  max_retries: 3
  retry_delay: 5
  
  # 监控配置
  storage_usage_threshold: 0.8  # 80%
  file_count_threshold: 10000
  monitor_interval: 3600

# ==================== 服务配置 ====================
server:
  port: 8000
  host: "0.0.0.0"
  debug: false
  enable_cors: true
  static_path: "static"
  max_upload_size: 100  # MB

# ==================== 安全配置 ====================
security:
  enable_https: false
  ssl_cert: ""
  ssl_key: ""
  session_secret: "your-secret-key-here"
  session_expire: 86400
  enable_api_auth: false
  api_key: "your-api-key-here"

# ==================== 爬虫服务配置 ====================
crawler_service:
  max_processes: 5
  task_timeout: 1800
  result_cache_time: 3600
  enable_monitoring: true
  monitor_interval: 30
  cpu_warning_threshold: 80
  memory_warning_threshold: 85
  disk_warning_threshold: 90

# ==================== 任务管理配置 ====================
task_management:
  max_queue_size: 100
  max_retry_count: 3
  retry_interval: 60
  status_check_interval: 10
  result_retention_days: 30

# ==================== 性能优化配置 ====================
performance:
  enable_cache: true
  cache_size_limit: 100
  enable_compression: true
  enable_async: true
  async_queue_size: 50
  async_timeout: 300

# ==================== 监控配置 ====================
monitoring:
  enable_system_monitor: true
  data_retention_days: 7
  collection_interval: 60
  enable_alerts: true
  alerts:
    cpu_threshold: 80
    memory_threshold: 85
    disk_threshold: 90
    response_time_threshold: 5000

# ==================== 开发环境配置 ====================
development:
  enable_hot_reload: false
  enable_debug_toolbar: false
  enable_detailed_errors: false
  test_mode: false

# ==================== 平台特定配置 ====================
xhs:
  search_note_type: "video"  # ALL, VIDEO, IMAGE
  xhs_specified_id_list: []
  xhs_creator_id_list: []

douyin:
  publish_time_type: 0
  dy_specified_id_list: []
  dy_creator_id_list: []

kuaishou:
  ks_specified_id_list: []
  ks_creator_id_list: []

bilibili:
  all_day: false
  start_day: "2024-01-01"
  end_day: "2024-01-31"
  bili_specified_id_list: []
  bili_creator_id_list: []
  creator_mode: false

weibo:
  weibo_specified_id_list: []
  weibo_creator_id_list: []

tieba:
  tieba_specified_id_list: []
  tieba_name_list: []
  tieba_creator_url_list: []

zhihu:
  zhihu_specified_id_list: []
  zhihu_creator_url_list: []

# ==================== 评论配置 ====================
comments:
  max_comments_count_single_notes: 100
  max_sub_comments_count_single_notes: 50

# ==================== 联系人配置 ====================
contacts:
  max_contacts_count_single_notes: 100

# ==================== 动态配置 ====================
dynamics:
  max_dynamics_count_single_notes: 100

# ==================== 词云配置 ====================
wordcloud:
  enable_get_wordcloud: false
  custom_words:
    "零几": "年份"
    "高频词": "专业术语"
  stop_words_file: "./docs/hit_stopwords.txt"
  font_path: "./docs/STZHONGS.TTF"

# ==================== 兼容性配置 ====================
ua: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0'
save_login_state: true
cookies: ""
account_id: null
start_page: 1
crawler_max_comments_count_singlenotes: 10
sort_type: "popularity_descending"
publish_time_type: 0
xhs_specified_note_url_list: [
  "https://www.xiaohongshu.com/explore/66fad51c000000001b0224b8?xsec_token=AB3rO-QopW5sgrJ41GwN01WCXh6yWPxjSoFI9D5JIMgKw=&xsec_source=pc_search"
]
start_day: '2024-01-01'
end_day: '2024-01-01'
all_day: false
creator_mode: true
start_contacs_page: 1
crawler_max_contacs_count_singlenotes: 100
crawler_max_dynamics_count_singlenotes: 50 